### ISSUE TITLE
[issue].  DOI assignment

### ISSUE THREAD

**Issue by rcjantz** [dibbs-vdc/ccql#21]
DOIs should be created automatically for VDC resources.  To do this, we will need to apply for a new prefix (unique to VDC) and then start using the EZID API to create DOIs.

**Comment by jkim-ru** [comment]
Note: Fake DOI generation was added with ticket #49. This will be need to be updated with #52 once we migrate to Hyrax 2.0.0.

**Comment by jkim-ru** [comment]
We may need to provide the option to manually enter in a DOI for resources.

Note from Ron
>In some cases, the DOIs I provided were legitimate DOIs.  Can you add some logic that doesn't replace a DOI with a dummy DOI, assuming the user has provided the DOI.  This is a fix that can be for V2.

Note from Janice
> I took out the ability to manually add DOIs in v1 because they were supposed to be system generated.  We can put back the DOI input field for v2, and only generate a DOI if one wasn't provided by the user. In that case, DOIs would never be required, even for open access resources.

**Comment by rcjantz** [comment]
We can set up the EZID API using test DOIs (that disappear after two weeks).  The following URL has code snippets for python, PERL, and PHP - https://ezid.cdlib.org/doc/apidoc.html#testing-the-api
