### ISSUE TITLE
[Issue] DOIs for collections

### ISSUE THREAD

**Issue by rcjantz** [dibbs-vdc/ccql#22]
We have decided to assign DOIs to resources.  Do we want to also assign a DOI to the project/collection.  Note, that we do assign DOIs to collections in RUcore.

**Comment by jkim-ru** [comment]
I think it was agreed at a previous meeting that we will not assign DOIs to projects or collections.

**Comment by rcjantz** [comment]
Janice,

You are correct.  Although we do assign DOIs to collections in RUcore, Grace has stressed that the DOIs should point to resources.  So, yes, we will not assign DOIs to projects/collection in the VDC.

Ron


________________________________
