### ISSUE TITLE
[Issue]. More than one license

### ISSUE THREAD

**Issue by rcjantz** [dibbs-vdc/ccql#25]
With multiple files included in a zip file, it may be necessary to have more than one license.  For example, the license for software may be different that for the data.

**Comment by anniekj** [comment]
I agree with Robert that there should be multiple license choices. This is not just because of multiple files...data may have already been posted elsewhere (FigShare, Zenodo, etc.) with a CC0 license.

**Comment by jkim-ru** [comment]
From Grace:

There should not be multiple license choices. A difference license requires new resource metadata and the two objects can be linked in the relation field.
