### ISSUE TITLE
[Issue] Clarification of Extent and File size

### ISSUE THREAD

**Issue by rcjantz** [dibbs-vdc/ccql#26]
The extent metadata field is to be used to indicate the number of files in a resource.  Should extent be specified at both the project and resource level? Ultimately file size should be computed automatically.  In the meantime, should this be a free text field?  Examples would help, e.g. 10MB, 3GB, 1TB, etc.

**Comment by jkim-ru** [comment]
Just an update --

As of now, based on a meeting with Grace, the Collection size is going to be a free text field.  Examples were added as a "hint" with issue #36.

Vanilla Hyrax has extent information at the Collection level (labeled "Total Items"), and I left that as is. However, there's no VDC-specific extent predicate defined for the collection like it is at the Resource level.  I can't remember if Grace specifically said yes or no for extent at the Collection level at the last meeting.

Also, vanilla Hyrax computes the file size at the collection level. I left that as is.

**Comment by rcjantz** [comment]
Janice,

Collection size as free text is fine.


Per my earlier question,  I assume "total items" will continue to accumulate as I upload resources over time?  Extent at the collection level is what we agreed upon.  And per Grace's earlier note, a zip file will be considered just one file (i.e. we won't worry in V1 about how many files are encapsulated within the zip).


So, a question about file size.  When I am creating a project, I will estimate the project/collection size (e.g. 10 GB). This is an estimate of storage space required for this collection.  But then Hyrax also computes the file size for each resource?  I think we are dealing with two numbers here - the estimated storage for the collection and the specific file size for each resource that is computed by Hyrax.  The issue here is also related to a brief discussion we had in our meeting that the infrastructure team would need to allocate storage based on a user's estimate of collection size.  Are you keeping both numbers, i.e. the total project size estimate and the file size for each resource?


Ron


________________________________

**Comment by jkim-ru** [comment]
> Per my earlier question,  I assume "total items" will continue to accumulate as I upload resources over time?

It should. I haven't looked specifically at the code that does this, but that's what I'm seeing when I tried things out.

> But then Hyrax also computes the file size for each resource?

I believe Vanilla Hyrax does this. When files are uploaded for a work/resource, a FileSet object is created for each file, which stores information like file size, mime type, etc.  

> Are you keeping both numbers, i.e. the total project size estimate and the file size for each resource?

Yes. I added "collectionSize" based on the metadata spreadsheet, and this represents the total project size estimate.  This will not change unless the user updates it.

The vanilla Hyrax application stores file sizes for each file uploaded as a member of a resource. It's not displayed, though.

The "Size" of the collection is part of the vanilla Hyrax application, and it maintains the accumulated size of  all files associated with works in the collection. This is displayed as part of the vanilla Hyrax application, and I left it as is.

**Comment by jkim-ru** [comment]
> Extent at the collection level is what we agreed upon.

I'll to talk to Grace about what metadata predicate we should use for this. I assume it'll be ``https://datacollaboratory.org/collection#extent`` but I'll ask to make sure the spreadsheet is updated (just so I don't get confused).

**Comment by jkim-ru** [comment]
I just spoke briefly to Grace about extent in Collections.  We're not going to add the extent at the Collection level. However, we can keep the vanilla Hyrax functionality for "Size" and "Total Items" (which is essentially extent).

**Comment by jkim-ru** [comment]
I'm closing this issue. I think it's been resolved. Please feel free to open it up again, if it makes sense.
