### ISSUE TITLE
Transfer functionality

### ISSUE THREAD

**Issue by anniekj** [dibbs-vdc/ccql#35]
I can't seem to figure out how to transfer ownership of a work. Option should be in dashboard but it's not there.

**Comment by jkim-ru** [comment]
I just tried it out.

1. From the Dashboard, I went to the "Transfer of Ownership" section, and clicked on "Select works to transfer".
2. I was redirected to the "My Works" view, where I selected a test work, clicked on the drop down Action, and selected "Transfer Ownership of Work".
3. I was redirected to a "Transfer ownership" page, where I had to type in your email address to find you.
4. I then typed in a comment and clicked on "Transfer".
5. Then, I was redirected back to my dashboard, where I could see information about the work that I'm attempting to transfer. 

I don't know if you get any notification, but if you do, please let me know.

**Comment by jkim-ru** [comment]
Annie, actually, I just reread your issue. I updated my last comment with a screenshot. Is this what you see in your dashboard? If not, can you post a screenshot?

**Comment by anniekj** [comment]
Yes! I got it! Thanks. Apologies, I guess this is a non-issue.

**Comment by jkim-ru** [comment]
Nice! One down... so many to go...
