### ISSUE TITLE
Proxies

### ISSUE THREAD

**Issue by rcjantz** [dibbs-vdc/ccql#47]
What is the purpose of "Manage Proxies"?

**Comment by jkim-ru** [comment]
I found this one link: http://samvera.github.io/works-testing.html#grant-proxy-authority-to-another-user

> Grant proxy authority to another user
Use case: Faculty member wants to deposit her works in the repository but delegates this task to her lab manager to deposit, describe, and manage Works on her behalf.

> Proxy Users may deposit, edit, and delete Works that are owned by other users. From the Dashboard, scroll down to the Manage Proxies. From the Authorized Proxies search menu, select a Users. Users available for proxy select must have logged into the repository in order to be found. When a User has been authorized as a Proxy, they will receive a Notification upon their next login.

I didn't know that this is what it was for until now. I think we've talked about this before, and it seems like it's something we want to make use of.

**Comment by jkim-ru** [comment]
Just an additional note. I tried out a proxy in Hyrax 1.0.4, and it seems to be working. Hyrax has a hidden field called "depositor", which is currently set to the email of the person that created the work.  When a proxy is enabled, a person can submit a work on behalf of someone, and when that happens, the "depositor" is set to someone other than the person doing the actual submit.
