### ISSUE TITLE
[bug] Creator name for a work

### ISSUE THREAD

**Issue by rcjantz** [dibbs-vdc/ccql#5]
When creating a new work for an established project, the creator name is set (apparently) to the creator of the project and can't be changed.  See screen shot.
![screen shot 2017-10-04 at 2 13 26 pm](https://user-images.githubusercontent.com/32523643/31192384-14c17dce-a90f-11e7-9057-ef9e1948ba9d.png)

**Comment by jkim-ru** [comment]
This is now a drop down of all of the approved users within the VDC. It can be changed.
