### ISSUE TITLE
[Issue] How is access defined?

### ISSUE THREAD

**Issue by rcjantz** [dibbs-vdc/ccql#6]
In creating a work, access can be private, embargo, open, or "Rutgers".  Embargo and open are clear.  How is "private" defined.  For "Rutgers", if a user signs in from another institution, does his/her institution display.  How is authorization implemented?  Is this done by restricting to IP addresses for an institution?

**Comment by jkim-ru** [comment]
Clarifications regarding the "Institution" visibility access:

* Currently, we have the "Institution" configured to be displayed as "Rutgers" (which should be renamed to something like "VDC" instead). 
* From what I can tell, the Institution-level visibility corresponds to anyone that is registered and logged in to the application. So, if you're a registered user, and you're logged in, you should be able to view all works and collections that are given the "Institution" visibility status. To contrast, "open" works can be viewed without even being logged in.

Clarification regarding "Private" visibility access:

* If a work is marked private, one way of giving authorization to another use or group of users is via the "share" tab that is visible when editing a work.

**Comment by jkim-ru** [comment]
Closing this for now, but please feel free to open it if you have a follow-up question!
