### ISSUE TITLE
[Bug] No results for empty project/works search

### ISSUE THREAD

**Issue by rcjantz** [dibbs-vdc/ccql#7]
Selecting "Projects Created" or "Works Created" on the left bar (see screen shot), the comment "No results found for your search" is displayed.  This should display all the projects or all the works.
![screen shot 2017-10-04 at 2 28 41 pm](https://user-images.githubusercontent.com/32523643/31192988-c3c02068-a910-11e7-87da-9a17735796d6.png)

**Comment by jkim-ru** [comment]
I messed this up early on without realizing it.  I restored it recently. The important part is that the vanilla Hyrax expects the ```to_s``` method in ```app/models/user.rb``` to return the user's email address, which is in turn used to create solr queries. Eventually, we should change this to not be email, but the uuid instead. However, I'm going to mark this as closed for now.
